# Generated by Django 6.0.4 on 2026-05-13 11:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('civility', models.CharField(choices=[('Madame', 'Madame'), ('Monsieur', 'Monsieur')], max_length=10, verbose_name='civilité')),
                ('birth_date', models.DateField(verbose_name='date de naissance')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='FR', verbose_name='téléphone')),
                ('professional_situation', models.CharField(choices=[('working', 'En emploi'), ('retired', 'À la retraite'), ('jobless', 'Sans emploi'), ('student', 'En étude')], max_length=20, verbose_name='situation professionnelle')),
                ('structure_name', models.CharField(blank=True, max_length=255, verbose_name='nom de la structure')),
                ('structure_address', models.CharField(blank=True, max_length=255, verbose_name='adresse de la structure')),
                ('structure_postal_code', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Entrez un code postal valide à 5 chiffres.')], verbose_name='code postal de la structure')),
                ('structure_city', models.CharField(blank=True, max_length=100, verbose_name='ville de la structure')),
                ('job_title', models.CharField(max_length=255, verbose_name='métier')),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Entrez un code postal valide à 5 chiffres.')], verbose_name='code postal')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('jobirl_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='identifiant utilisateur jobirl')),
                ('jobirl_user_token', models.CharField(blank=True, max_length=128, verbose_name='token utilisateur jobirl')),
            ],
            options={
                'verbose_name': 'mentor',
                'verbose_name_plural': 'mentors',
            },
            bases=('techpourtoutes.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
