# Generated by Django 6.0.4 on 2026-05-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='structure_address',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='structure_city',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='structure_postal_code',
        ),
    ]
