# Generated by Django 6.0.4 on 2026-05-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='professional_situation',
            field=models.CharField(choices=[('working', 'En emploi'), ('retired', 'À la retraite'), ('jobless', 'Sans emploi'), ('student', 'En étude')], max_length=20, verbose_name='situation professionnelle'),
        ),
    ]
