# Generated by Django 6.0.4 on 2026-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0002_alter_mentor_professional_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='jobirl_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='identifiant utilisateur jobirl'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='jobirl_user_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='token utilisateur jobirl'),
        ),
    ]
