# Generated by Django 6.0.4 on 2026-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0002_remove_mentor_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiration du jeton de connexion'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_token_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='hash du jeton de connexion'),
        ),
    ]
