# Generated by Django 6.0.4 on 2026-05-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0003_mentor_jobirl_user_id_mentor_jobirl_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='date de naissance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='civility',
            field=models.CharField(choices=[('Madame', 'Madame'), ('Monsieur', 'Monsieur')], default='Madame', max_length=10, verbose_name='civilité'),
            preserve_default=False,
        ),
    ]
