# Generated by Django 6.0.4 on 2026-05-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0003_user_login_token_expires_at_user_login_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="datetime d'expiration du token de connexion envoyé par mail au user"),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_token_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name="hash du token de connexion envoyé par mail à l'utilisateur"),
        ),
    ]
