# Generated by Django 6.0.4 on 2026-05-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0004_mentor_address_mentor_birth_date_mentor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='structure_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse de la structure'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='structure_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville de la structure'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='structure_postal_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='code postal de la structure'),
        ),
    ]
