# Generated by Django 6.0.4 on 2026-05-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0004_alter_user_login_token_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='city',
        ),
    ]
