# Generated by Django 6.0.4 on 2026-05-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0005_remove_mentor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brevo_sync_enabled',
            field=models.BooleanField(default=True, help_text="Si décoché, ce compte n'est pas synchronisé vers Brevo.", verbose_name='synchroniser avec Brevo'),
        ),
    ]
