# Generated by Django 6.0.4 on 2026-05-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0007_rename_mentor_pro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pro',
            options={'verbose_name': 'pro', 'verbose_name_plural': 'pros'},
        ),
    ]
