# Generated by Django 6.0.4 on 2026-05-29 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


def backfill_mentor_engagements(apps, _):
    Pro = apps.get_model("techpourtoutes", "Pro")
    Pro.objects.filter(jobirl_user_id__isnull=False).update(engagements=["mentor"])


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0008_alter_pro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='engagements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mentor', 'Mentorer'), ('internships', 'Accueillir une stagiaire'), ('work_ambassador', 'Pitcher mon métier'), ('training_ambassador', 'Pitcher ma formation'), ('sponsor', 'Devenir mécène')], max_length=30), blank=True, default=list, verbose_name='engagements'),
        ),
        migrations.RunPython(backfill_mentor_engagements, migrations.RunPython.noop),
    ]
