# Generated by Django 6.0.4 on 2026-06-02 09:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0009_add_pro_engagements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='engagements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mentor', 'mentorer'), ('internships', 'accueillir une stagiaire'), ('work_ambassador', 'pitcher son métier'), ('training_ambassador', 'pitcher sa formation'), ('sponsor', 'devenir mécène')], max_length=30), blank=True, default=list, verbose_name='engagements'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='professional_situation',
            field=models.CharField(choices=[('working', 'En emploi'), ('retired', 'À la retraite'), ('jobless', 'Sans emploi')], max_length=20, verbose_name='situation professionnelle'),
        ),
    ]
