# Generated by Django 6.0.4 on 2026-06-03 11:09

import django.contrib.postgres.fields
import django.core.validators
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0010_alter_pro_engagements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('identifier', models.CharField(max_length=20, unique=True, verbose_name="identifiant de l'établissement")),
                ('name', models.CharField(max_length=255, verbose_name="nom de l'établissement")),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
            },
        ),
        migrations.AddField(
            model_name='pro',
            name='structure_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='identifiant de la structure'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='engagements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mentor', 'mentorer'), ('internships', 'accueillir une stagiaire'), ('work_ambassador', 'pitcher son métier'), ('training_ambassador', 'pitcher sa formation'), ('sponsor', 'devenir mécène'), ('workshops', 'organiser un atelier')], max_length=30), blank=True, default=list, verbose_name='engagements'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='FR', verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Entrez un code postal valide à 5 chiffres.')], verbose_name='code postal'),
        ),
    ]
