# Generated by Django 6.0.4 on 2026-06-03 12:17

import unicodedata

from django.db import migrations, models


def backfill_name_normalized(apps, schema_editor):
    School = apps.get_model("techpourtoutes", "School")

    def normalize(text):
        return "".join(c for c in unicodedata.normalize("NFKD", text) if not unicodedata.combining(c))

    schools = list(School.objects.all())
    for school in schools:
        school.name_normalized = normalize(school.name)
    School.objects.bulk_update(schools, ["name_normalized"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0011_school_pro_structure_id_alter_pro_engagements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='name_normalized',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.RunPython(backfill_name_normalized, migrations.RunPython.noop),
    ]
