# Generated by Django 6.0.4 on 2026-06-03 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0012_school_name_normalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Saisissez une adresse mail valide.')], verbose_name='adresse email'),
        ),
    ]
