# Generated by Django 6.0.4 on 2026-06-03 13:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Entrez un code postal valide à 5 chiffres.')], verbose_name='code postal'),
        ),
        migrations.CreateModel(
            name='WorkshopRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('type', models.CharField(choices=[('enquete_techpourtoutes', "L'enquête TechPourToutes"), ('future_of_tech', 'Future of Tech'), ('future_of_ia', 'Future of IA'), ('future_of_cyber', 'Future of Cyber')], max_length=30, verbose_name="type d'atelier")),
                ('remark', models.TextField(blank=True, verbose_name='remarque')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_requests', to='techpourtoutes.pro', verbose_name='pro')),
            ],
            options={
                'verbose_name': "demande d'atelier",
                'verbose_name_plural': "demandes d'atelier",
            },
        ),
    ]
