# Generated by Django 6.0.4 on 2026-06-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0014_alter_pro_postal_code_workshoprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='professional_situation',
            field=models.CharField(choices=[('working', 'En emploi'), ('student', 'En étude'), ('retired', 'À la retraite'), ('jobless', 'Sans emploi')], max_length=20, verbose_name='situation professionnelle'),
        ),
    ]
