# Generated by Django 6.0.4 on 2026-06-08 12:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0015_alter_pro_professional_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='engagements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mentor', 'mentorer'), ('internships', 'accueillir une stagiaire'), ('work_ambassador', 'pitcher son métier'), ('training_ambassador', 'devenir ambassadrice étudiante'), ('sponsor', 'devenir mécène'), ('workshops', 'organiser un atelier')], max_length=30), blank=True, default=list, verbose_name='engagements'),
        ),
    ]
