# Generated by Django 6.0.4 on 2026-06-11 16:16

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0016_alter_pro_engagements'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherEdSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('full_name', models.CharField(max_length=255, verbose_name="nom de l'établissement")),
                ('full_name_normalized', models.CharField(blank=True, editable=False, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='acronyme')),
                ('name_normalized', models.CharField(blank=True, editable=False, max_length=255)),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('uai', models.CharField(blank=True, max_length=20, verbose_name='UAI')),
                ('conferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CGE', 'CGE'), ('CDEFI', 'CDEFI'), ('FU', 'FU')], max_length=10), blank=True, default=list, verbose_name='conférences')),
            ],
            options={
                'verbose_name': "établissement d'enseignement supérieur",
                'verbose_name_plural': "établissements d'enseignement supérieur",
                'constraints': [models.UniqueConstraint(condition=models.Q(('uai', ''), _negated=True), fields=('uai', 'name'), name='unique_higher_ed_uai_name'), models.UniqueConstraint(condition=models.Q(('siret', ''), _negated=True), fields=('siret', 'name'), name='unique_higher_ed_siret_name')],
            },
        ),
    ]
