# Generated by Django 6.0.4 on 2026-06-11 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0017_higheredschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('course', models.CharField(max_length=255, verbose_name='cursus')),
                ('higher_ed_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_experiences', to='techpourtoutes.higheredschool', verbose_name="établissement d'enseignement supérieur")),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_experiences', to='techpourtoutes.pro', verbose_name='pro')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
            },
        ),
    ]
