# Generated by Django 6.0.4 on 2026-06-11 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0018_trainingexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Entrez un code postal valide à 5 chiffres.')], verbose_name='code postal'),
        ),
    ]
