# Generated by Django 6.0.4 on 2026-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0019_alter_pro_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='métier'),
        ),
    ]
