# Generated by Django 6.0.4 on 2026-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0020_alter_pro_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='faveod_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='identifiant faveod'),
        ),
    ]
