# Generated by Django 6.0.4 on 2026-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0021_add_faveod_id_to_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brevo_sync_enabled',
            field=models.BooleanField(default=False, help_text="Si décoché, ce compte n'est pas synchronisé vers Brevo.", verbose_name='synchroniser avec Brevo'),
        ),
    ]
