# Generated by Django 6.0.4 on 2026-07-08 08:18

import techpourtoutes.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0022_alter_user_brevo_sync_enabled'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pro',
            managers=[
                ('objects', techpourtoutes.models.user.ActiveUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', techpourtoutes.models.user.ActiveUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si décoché, ce compte est désactivé', verbose_name='est un compte activé'),
        ),
    ]
