# Generated by Django 6.0.4 on 2026-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0023_alter_pro_managers_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="nombre de tentatives de saisie du code de changement d'adresse email"),
        ),
        migrations.AddField(
            model_name='user',
            name='email_change_code_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name="hash du code de changement d'adresse email"),
        ),
    ]
