# Generated by Django 6.0.4 on 2026-07-20 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_pro_to_user(apps, schema_editor):
    TrainingExperience = apps.get_model("techpourtoutes", "TrainingExperience")
    TrainingExperience.objects.filter(pro__isnull=False).update(user=models.F("pro"))


def copy_user_to_pro(apps, schema_editor):
    TrainingExperience = apps.get_model("techpourtoutes", "TrainingExperience")
    TrainingExperience.objects.filter(user__isnull=False).update(pro=models.F("user"))


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0024_user_email_change_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexperience',
            name='level',
            field=models.CharField(blank=True, choices=[('troisieme', 'Troisième'), ('seconde', 'Seconde'), ('premiere', 'Première'), ('terminale', 'Terminale'), ('bac_1', 'Bac +1'), ('bac_2', 'Bac +2'), ('bac_3', 'Bac +3'), ('bac_4', 'Bac +4'), ('bac_5', 'Bac +5'), ('bac_5_plus', 'Au-delà de bac +5')], max_length=20, verbose_name='niveau'),
        ),
        migrations.AddField(
            model_name='trainingexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de début'),
        ),
        migrations.AddField(
            model_name='trainingexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AddField(
            model_name='trainingexperience',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_experiences', to='techpourtoutes.school', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='trainingexperience',
            name='higher_ed_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_experiences', to='techpourtoutes.higheredschool', verbose_name="établissement d'enseignement supérieur"),
        ),
        migrations.AddField(
            model_name='trainingexperience',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_experiences', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.RunPython(copy_pro_to_user, copy_user_to_pro),
        migrations.RemoveField(
            model_name='trainingexperience',
            name='pro',
        ),
        migrations.AlterField(
            model_name='trainingexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_experiences', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
