# Generated by Django 6.0.4 on 2026-07-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0024_user_email_change_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="datetime d'expiration du code de changement d'adresse mail"),
        ),
        migrations.AddField(
            model_name='user',
            name='login_code_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='nombre de tentatives de saisie du code de connexion'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="datetime d'expiration du code de connexion envoyé par mail au user"),
        ),
        migrations.AddField(
            model_name='user',
            name='login_code_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name="hash du code de connexion envoyé par mail à l'utilisateur"),
        ),
    ]
