# Generated by Django 6.0.4 on 2026-07-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0025_user_email_change_code_expires_at_and_more'),
        ('techpourtoutes', '0026_trainingexperience_ordering_and_unique_period'),
    ]

    operations = [
    ]
