# Generated by Django 6.0.4 on 2026-07-28 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0027_trainingexperience_ordering_and_unique_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='mis à jour le')),
                ('uai', models.CharField(max_length=20, unique=True, verbose_name='UAI')),
                ('name', models.CharField(max_length=255, verbose_name="nom de l'établissement")),
                ('name_normalized', models.CharField(blank=True, editable=False, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('education_level', models.CharField(choices=[('non_sup', 'Lycée'), ('sup', 'Supérieur'), ('both', 'Les deux')], max_length=10)),
                ('matches_digital_domain', models.BooleanField(default=False, verbose_name='formation numérique/informatique repérée')),
                ('matches_apprenticeship', models.BooleanField(default=False, verbose_name='formation en apprentissage repérée')),
            ],
            options={
                'verbose_name': 'établissement éligible',
                'verbose_name_plural': 'établissements éligibles',
            },
        ),
    ]
