# Generated by Django 6.0.4 on 2026-07-22 17:11

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import techpourtoutes.models.user
from django.conf import settings
from django.db import migrations, models

# civility/phone/postal_code move from the `pro` MTI child up to the `user` parent. The ORM cannot
# hold these fields on both User and Pro at once (MTI local-field clash), so the schema change is
# expressed as raw SQL (database) decoupled from the field move (state) via SeparateDatabaseAndState.
MOVE_FIELDS_FORWARD = [
    "ALTER TABLE techpourtoutes_user ADD COLUMN civility varchar(10) NOT NULL DEFAULT ''",
    "ALTER TABLE techpourtoutes_user ALTER COLUMN civility DROP DEFAULT",
    "ALTER TABLE techpourtoutes_user ADD COLUMN phone varchar(128) NOT NULL DEFAULT ''",
    "ALTER TABLE techpourtoutes_user ALTER COLUMN phone DROP DEFAULT",
    "ALTER TABLE techpourtoutes_user ADD COLUMN postal_code varchar(5) NOT NULL DEFAULT ''",
    "ALTER TABLE techpourtoutes_user ALTER COLUMN postal_code DROP DEFAULT",
    """
    UPDATE techpourtoutes_user AS u
    SET civility = p.civility, phone = p.phone, postal_code = p.postal_code
    FROM techpourtoutes_pro AS p
    WHERE p.user_ptr_id = u.id
    """,
    "ALTER TABLE techpourtoutes_pro DROP COLUMN civility",
    "ALTER TABLE techpourtoutes_pro DROP COLUMN phone",
    "ALTER TABLE techpourtoutes_pro DROP COLUMN postal_code",
]

MOVE_FIELDS_REVERSE = [
    "ALTER TABLE techpourtoutes_pro ADD COLUMN civility varchar(10) NOT NULL DEFAULT ''",
    "ALTER TABLE techpourtoutes_pro ADD COLUMN phone varchar(128) NOT NULL DEFAULT ''",
    "ALTER TABLE techpourtoutes_pro ADD COLUMN postal_code varchar(5) NOT NULL DEFAULT ''",
    """
    UPDATE techpourtoutes_pro AS p
    SET civility = u.civility, phone = u.phone, postal_code = u.postal_code
    FROM techpourtoutes_user AS u
    WHERE p.user_ptr_id = u.id
    """,
    "ALTER TABLE techpourtoutes_user DROP COLUMN civility",
    "ALTER TABLE techpourtoutes_user DROP COLUMN phone",
    "ALTER TABLE techpourtoutes_user DROP COLUMN postal_code",
]


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0027_trainingexperience_ordering_and_unique_period'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(MOVE_FIELDS_FORWARD, MOVE_FIELDS_REVERSE),
            ],
            state_operations=[
                migrations.RemoveField(model_name='pro', name='civility'),
                migrations.RemoveField(model_name='pro', name='phone'),
                migrations.RemoveField(model_name='pro', name='postal_code'),
                migrations.AddField(
                    model_name='user',
                    name='civility',
                    field=models.CharField(blank=True, choices=[('Madame', 'Madame'), ('Monsieur', 'Monsieur')], max_length=10, verbose_name='civilité'),
                ),
                migrations.AddField(
                    model_name='user',
                    name='phone',
                    field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='FR', verbose_name='téléphone'),
                ),
                migrations.AddField(
                    model_name='user',
                    name='postal_code',
                    field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Entrez un code postal valide à 5 chiffres.')], verbose_name='code postal'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
            ],
            options={
                'verbose_name': 'bénéficiaire',
                'verbose_name_plural': 'bénéficiaires',
            },
            bases=('techpourtoutes.user',),
            managers=[
                ('objects', techpourtoutes.models.user.ActiveUserManager()),
            ],
        ),
    ]
