# Generated by Django 6.0.4 on 2026-07-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0027_merge_20260724_1656'),
        ('techpourtoutes', '0029_move_phone_to_user'),
    ]

    operations = [
    ]
