# Generated by Django 6.0.4 on 2026-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0030_move_phone_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higheredschool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='higheredschool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='trainingexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='trainingexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_change_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="nombre de tentatives de saisie du code de changement d'adresse mail"),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_change_code_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name="hash du code de changement d'adresse mail"),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='mis à jour le'),
        ),
    ]
