# Generated by Django 6.0.4 on 2026-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0034_alter_user_first_name_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexperience',
            name='course',
            field=models.CharField(max_length=255, verbose_name='filière'),
        ),
    ]
