# Generated by Django 6.0.4 on 2026-08-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0037_drop_higher_ed_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='structure_id',
        ),
    ]
