# Generated by Django 6.0.4 on 2026-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0038_remove_pro_structure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='cog_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='COG de la commune'),
        ),
        migrations.AlterField(
            model_name='school',
            name='parent_onisep_id',
            field=models.CharField(blank=True, max_length=20, verbose_name="identifiant Onisep de l'université de rattachement"),
        ),
        migrations.AlterField(
            model_name='school',
            name='region_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='COG de région'),
        ),
    ]
