# Generated by Django 6.0.4 on 2026-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0040_formation_search_and_training_experience_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=350, verbose_name="nom de l'établissement"),
        ),
    ]
