# Generated by Django 6.0.4 on 2026-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0041_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='higher_ed',
            field=models.BooleanField(default=False, verbose_name='enseignement supérieur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='secondary',
            field=models.BooleanField(default=False, verbose_name='enseignement secondaire'),
        ),
    ]
