# Generated by Django 6.0.4 on 2026-08-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0044_training_experience_out_of_scope_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='legal_representative_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email de la personne responsable légale'),
        ),
    ]
