# Generated by Django 6.0.4 on 2026-08-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0045_add_beneficiary_legal_representative_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='legal_representative_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nom de la personne responsable légale'),
        ),
    ]
