# Generated by Django 6.0.4 on 2026-08-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0047_move_faveod_id_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='type_acronym',
            field=models.CharField(blank=True, max_length=50, verbose_name='sigle du type de formation'),
        ),
    ]
