# Generated by Django 6.0.4 on 2026-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0047_move_faveod_id_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='recommandé'),
        ),
        migrations.AlterField(
            model_name='school',
            name='training_ambassador_eligible',
            field=models.BooleanField(default=False, verbose_name='éligible ambassadrice étudiante'),
        ),
    ]
