# Generated by Django 6.0.4 on 2026-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0048_add_school_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='domain',
            field=models.TextField(blank=True, verbose_name='domaine de formation'),
        ),
    ]
