# Generated by Django 6.0.4 on 2026-09-01 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0049_add_school_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='domaines de formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='sub_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='sous-domaines de formation'),
        ),
    ]
