# Generated by Django 6.0.4 on 2026-09-02 13:59

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0050_formation_domains_and_sub_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='mis à jour le')),
                ('title', models.CharField(verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('subcategory', models.CharField(max_length=100, verbose_name='sous-catégorie')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('location_type', models.CharField(choices=[('physical', 'En présentiel'), ('online', 'En ligne')], max_length=10, verbose_name='format')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='commune')),
                ('cog_code', models.CharField(blank=True, max_length=10, verbose_name='COG de la commune')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('ban_id', models.CharField(blank=True, max_length=30, verbose_name='identifiant BAN')),
                ('online_url', models.URLField(blank=True, verbose_name='lien de connexion')),
                ('event_url', models.URLField(blank=True, verbose_name="lien vers l'événement")),
                ('access_type', models.CharField(choices=[('candidacy', 'Candidature'), ('registration', 'Inscription'), ('open', 'Accès libre')], max_length=20, verbose_name="modalité d'inscription")),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='pending', max_length=20, verbose_name='statut')),
                ('organizer', models.CharField(verbose_name='organisateur')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='techpourtoutes.pro', verbose_name='pro')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', verbose_name='id')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='date and time at which a record was created', verbose_name='créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='date and time at which a record was last updated', verbose_name='mis à jour le')),
                ('title', models.CharField(verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('subcategory', models.CharField(max_length=100, verbose_name='sous-catégorie')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('location_type', models.CharField(choices=[('physical', 'En présentiel'), ('online', 'En ligne')], max_length=10, verbose_name='format')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='commune')),
                ('cog_code', models.CharField(blank=True, max_length=10, verbose_name='COG de la commune')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('ban_id', models.CharField(blank=True, max_length=30, verbose_name='identifiant BAN')),
                ('online_url', models.URLField(blank=True, verbose_name='lien de connexion')),
                ('event_url', models.URLField(blank=True, verbose_name="lien vers l'événement")),
                ('access_type', models.CharField(choices=[('candidacy', 'Candidature'), ('registration', 'Inscription'), ('open', 'Accès libre')], max_length=20, verbose_name="modalité d'inscription")),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='pending', max_length=20, verbose_name='statut')),
                ('organizer', models.CharField(verbose_name='organisateur')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='techpourtoutes.pro', verbose_name='pro')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical événement',
                'verbose_name_plural': 'historical événements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='mis à jour le')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='techpourtoutes.beneficiary', verbose_name='bénéficiaire')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='techpourtoutes.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'événement sauvegardé',
                'verbose_name_plural': 'événements sauvegardés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_events', through='techpourtoutes.SavedEvent', to='techpourtoutes.beneficiary', verbose_name='sauvegardé par'),
        ),
        migrations.AddConstraint(
            model_name='savedevent',
            constraint=models.UniqueConstraint(fields=('event', 'beneficiary'), name='unique_saved_event_per_beneficiary'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date')), models.Q(('end_date', models.F('start_date')), ('end_time__gte', models.F('start_time'))), _connector='OR'), name='event_ends_after_it_starts', violation_error_message="La fin de l'événement doit suivre son début."),
        ),
    ]
