# Generated by Django 6.0.4 on 2026-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0052_event_access_naming'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poi_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom du lieu'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='poi_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom du lieu'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('location_type', 'physical'), ('status', 'approved'), _negated=True), models.Q(('address', ''), ('poi_name', ''), _negated=True), _connector='OR'), name='approved_physical_event_names_a_place', violation_error_message='Un événement en présentiel doit porter une adresse ou un nom de lieu.'),
        ),
    ]
