# Generated by Django 6.0.4 on 2026-09-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techpourtoutes", "0054_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="subcategory",
            field=models.CharField(max_length=22, verbose_name="sous-catégorie"),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="subcategory",
            field=models.CharField(max_length=22, verbose_name="sous-catégorie"),
        ),
    ]
