# Generated by Django 6.0.4 on 2026-10-01 10:20

import techpourtoutes.utils.object_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0056_create_event_moderator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, max_length=255, storage=techpourtoutes.utils.object_storage.public_storage, upload_to='', verbose_name='visuel'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='alternative textuelle du visuel'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_credit',
            field=models.CharField(blank=True, max_length=255, verbose_name='crédit du visuel'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image',
            field=models.TextField(blank=True, max_length=255, verbose_name='visuel'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='alternative textuelle du visuel'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image_credit',
            field=models.CharField(blank=True, max_length=255, verbose_name='crédit du visuel'),
        ),
    ]
