# Generated by Django 6.0.4 on 2026-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpourtoutes', '0058_create_new_pro_features_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='has_requested_training_ambassador',
            field=models.BooleanField(default=False, verbose_name='a demandé à être mise en contact avec une ambassadrice'),
        ),
    ]
