exclude: "migrations"

repos:
  # Modernisation syntaxe Python
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: ["--py314-plus"]  # adapte à ta version Python

  # Modernisation syntaxe Django
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.30.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "6.0"]  # adapte à ta version Django

  # Vérifications générales
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending

  # Linter + formateur (remplace flake8 + isort)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # pyproject.toml
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.21.1
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: local
    hooks:
      - id: tailwind-build
        name: Build Tailwind CSS
        entry: uv run python manage.py tailwind build
        language: system
        files: \.(css|html)$
        pass_filenames: false
