"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
FAVICON_NAMEFILE = env("FAVICON_NAMEFILE", default="images/favicon-tpt")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
SITE_URL = env("HOST", default="https://localhost:8000").rstrip("/")
# Admin is mounted at this path; override in production to a non-guessable value.
ADMIN_URL = env("ADMIN_URL", default="admin").strip("/")
# Escape hatch to disable the admin 2FA requirement outside local dev (e.g. review apps).
DISABLE_ADMIN_2FA = env.bool("DISABLE_ADMIN_2FA", default=False)

# `manage.py seed` creates an admin account with a well-known-by-default password. Enabled by
# default in local dev (DEBUG); review apps opt in explicitly since they run with DEBUG=False.
SEED_ENABLED = env.bool("SEED_ENABLED", default=DEBUG)
SEED_ADMIN_EMAIL = env("SEED_ADMIN_EMAIL", default="admin@techpourtoutes.io")
SEED_ADMIN_PASSWORD = env("SEED_ADMIN_PASSWORD", default="admin")
DATABASES = {
    "default": {
        **env.db("DATABASE_URL"),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
    }
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.postgres",
    "django_extensions",
    "django_tailwind_cli",
    "django_cotton",
    "simple_history",
    "phonenumber_field",
    "anymail",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "axes",
    "waffle",
    # Apps techpourtoutes
    "techpourtoutes",
    "ui",
]

AUTH_USER_MODEL = "techpourtoutes.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "conf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "conf.context_processors.global_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "conf.wsgi.application"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "techpourtoutes.clients": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "techpourtoutes.services": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

# Auth settings
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_URL = "login_request"
LOGOUT_REDIRECT_URL = "/"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 90  # 90 days
SESSION_SAVE_EVERY_REQUEST = True

# Security hardening (production only; local dev and tests run over plain HTTP)
if not DEBUG:
    # The platform proxy terminates TLS and forwards plain HTTP with this header, letting
    # request.is_secure() recognise the original HTTPS request (cookies, redirect, HSTS).
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Start conservative; ramp up to 31536000 (1 year) once HTTPS is confirmed stable.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Email
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL", default="TechPourToutes <noreply@techpourtoutes.io>"
)
BREVO_API_KEY = env("BREVO_API_KEY", default="")
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "localhost"
    EMAIL_PORT = 1025
else:
    EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
    ANYMAIL = {"BREVO_API_KEY": BREVO_API_KEY}

# Jobirl API
JOBIRL_API_KEY = env("JOBIRL_API_KEY", default="")
JOBIRL_URL = env("JOBIRL_URL", default="")

# Schools import (data.education.gouv.fr)
HUWISE_API_KEY = env("HUWISE_API_KEY", default="")

# n8n webhooks
N8N_WORKSHOP_WEBHOOK_URL = env(
    "N8N_WORKSHOP_WEBHOOK_URL",
    default="https://n8n.yunohost.latitudes.cc/webhook/techpourtoutes-atelier",
)
N8N_WORKSHOP_WEBHOOK_BASIC_AUTH_USER = env("N8N_WORKSHOP_WEBHOOK_BASIC_AUTH_USER", default="")
N8N_WORKSHOP_WEBHOOK_BASIC_AUTH_PASSWORD = env(
    "N8N_WORKSHOP_WEBHOOK_BASIC_AUTH_PASSWORD", default=""
)

# Brevo contacts API
BREVO_PRO_LIST_ID = env.int("BREVO_PRO_LIST_ID", default=0)
BREVO_MANIFESTE_LIST_ID = env.int("BREVO_MANIFESTE_LIST_ID", default=0)
BREVO_SYNC_ENABLED = env.bool("BREVO_SYNC_ENABLED", default=False)

# Coalition engagement notification recipients
COALITION_INTERNSHIPS_RECIPIENTS = env.list(
    "COALITION_INTERNSHIPS_RECIPIENTS", default=["bonjour@techpourtoutes.io"]
)
COALITION_WORK_AMBASSADOR_RECIPIENTS = env.list(
    "COALITION_WORK_AMBASSADOR_RECIPIENTS", default=["bonjour@techpourtoutes.io"]
)
COALITION_TRAINING_AMBASSADOR_RECIPIENTS = env.list(
    "COALITION_TRAINING_AMBASSADOR_RECIPIENTS", default=["bonjour@techpourtoutes.io"]
)
COALITION_SPONSOR_RECIPIENTS = env.list(
    "COALITION_SPONSOR_RECIPIENTS", default=["bonjour@techpourtoutes.io"]
)
COALITION_ACCOUNT_DELETION_RECIPIENTS = env.list(
    "COALITION_ACCOUNT_DELETION_RECIPIENTS", default=["bonjour@techpourtoutes.io"]
)

# Celery
CELERY_BROKER_URL = env("REDIS_URL", default="redis://localhost:6379/0")
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_EAGER_PROPAGATES = True

# Cache and sessions. CACHE_URL should be a Redis instance.
# When Redis is available, sessions are stored there instead of the database.
if env("CACHE_URL", default=""):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": env("CACHE_URL"),
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"

# Rate limiting of public POST endpoints, as "<max_requests>/<window_seconds>" per client.
RATELIMIT_LOGIN = env("RATELIMIT_LOGIN", default="5/300")
RATELIMIT_EMAIL_CHANGE_RESEND = env("RATELIMIT_EMAIL_CHANGE_RESEND", default="3/300")

# django-axes — locks out repeated failed password logins (admin brute-force protection).
# Disabled in local dev (DEBUG); the test suite enables it explicitly where needed.
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",  # must come first
    "django.contrib.auth.backends.ModelBackend",
]
AXES_ENABLED = env.bool("AXES_ENABLED", default=not DEBUG)
AXES_FAILURE_LIMIT = env.int("AXES_FAILURE_LIMIT", default=5)
AXES_COOLOFF_TIME = 1  # hours before a lock-out expires
# Scope lock-outs to the (username, IP) pair so nobody can lock a real admin out globally.
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = True
# Resolve the client IP the same way as the rate limiter (1st X-Forwarded-For entry).
AXES_CLIENT_IP_CALLABLE = "techpourtoutes.ratelimit.client_ip"

# Matomo analytics (values differ per environment; leave empty to disable tracking)
MATOMO_URL = env("MATOMO_URL", default="").rstrip("/")
MATOMO_SITE_ID = env("MATOMO_SITE_ID", default="")

# Sentry
SENTRY_DSN = env("SENTRY_DSN", default="")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration()],
        send_default_pii=False,
    )


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-FR"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "ui/static"]

TAILWIND_CLI_USE_DAISY_UI = True
TAILWIND_CLI_SRC_CSS = BASE_DIR / "ui/source.css"

STORAGES = {
    "default": {  # for uploaded file ; this will change if we use S3
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {  # Configure static files storage to use WhiteNoise's optimized storage
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
